### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by threalboss** [maxenxe/HQ-Trivia-Bot#19]
keep on this error  

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "38x178+387+712" "answers.jpg" this most likely means the gm/convert binaries can't be found

and I do not know how to install tesseract-OCR and add it to your PATH environment variable.
most importantly the PATH environment variable. part

I am using a MacBook air

**Comment by threalboss** [comment]
it says 

> hqtriviabot@1.0.0 start /Users/noahschwartz/Desktop/hq/HQ-Trivia-Bot-master
> node bot.js

Screenshot done
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "38x178+387+712" "answers.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/noahschwartz/Desktop/hq/HQ-Trivia-Bot-master/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by maxenxe** [comment]
Search online for how to update your environment variables on Mac, or more precisely how to add graphics magic to environment variables
