### ISSUE TITLE
tesseract

### ISSUE THREAD

**Issue by julian2355** [maxenxe/HQ-Trivia-Bot#21]
C:\Users\julia\Desktop\hq>node bot.js
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\julia\AppData\Local\Temp\tmp-123127zvabRlPbwE2'
node-tesseract: Preprocessor cleanup
{ Error: Command failed: tesseract answers.jpg C:\Users\julia\AppData\Local\Temp\tmp-123127zvabRlPbwE2
'tesseract' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract answers.jpg C:\\Users\\julia\\AppData\\Local\\Temp\\tmp-123127zvabRlPbwE2' }

ive tried installing and adding to path 100 times

**Comment by maxenxe** [comment]
please show me your path

**Comment by julian2355** [comment]
https://gyazo.com/331ceccc466f002d171586ea4092f4b3

**Comment by julian2355** [comment]
fixed now im getting this Error: Error on response (503):null : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://www.google.com/search?hl=en&amp;q=%3A%20comreceptchalapijs%20error%20%20ba%3A%20%20%20%20%20nowe%20%40%20%20%20%20%20%E2%82%AC%20%20%20%20%20Which%20of%20thase%20is%20the%20correct%20pairing%20of%20capital%20city%20and%20country%3F%20%20Witiogon%20tewza%20%20%20%20%20&amp;start=0&amp;sa=N&amp;num=25&amp;ie=UTF-8&amp;oe=UTF-8&amp;gws_rd=ssl</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form action="index" method="post">
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b"></div>
<input type='hidden' name='q' value='EgRLvoIcGLX3wNUFIhkA8aeDS0AkGzhzBZIjoG2x2mmG183Br5-gMgFy'><input type="hidden" name="continue" value="https://www.google.com/search?hl=en&amp;q=%3A%20comreceptchalapijs%20error%20%20ba%3A%20%20%20%20%20nowe%20%40%20%20%20%20%20%E2%82%AC%20%20%20%20%20Which%20of%20thase%20is%20the%20correct%20pairing%20of%20capital%20city%20and%20country%3F%20%20Witiogon%20tewza%20%20%20%20%20&amp;start=0&amp;sa=N&amp;num=25&amp;ie=UTF-8&amp;oe=UTF-8&amp;gws_rd=ssl">
<input type="submit" name="submit" value="Submit" style="font-size:18px; padding:4px 0;"><br><br><br>
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

**Comment by maxenxe** [comment]
the only solution *

**Comment by momomaster** [comment]
how did you fix your original problem?
