### ISSUE TITLE
how do i add tesseract to my pat environment variable on mac

### ISSUE THREAD

**Issue by Anishrajeev210** [maxenxe/HQ-Trivia-Bot#22]

**Comment by Anishrajeev210** [comment]
and also what does this mean  at 

```
ChildProcess.onExit (/Users/anish/Downloads/HQ-Trivia-Bot-master/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5) code: 1, signal: null }
Anishs-MacBook-Pro:HQ-Trivia-Bot-master anish$
```
