### ISSUE TITLE
Unable to get answers!!!!!! Please help!!!!

### ISSUE THREAD

**Issue by PoonamChohdhary1991** [maxenxe/HQ-Trivia-Bot#26]
Admin@DESKTOP-527GMSJ MINGW64 ~/Desktop/HQ-Trivia-Bot (master)
$ node bot.js
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\Admin\AppData\Local\Temp
\tmp-5164wBfCIzGL8Bvb'
node-tesseract: Deleting 'C:\Users\Admin\AppData\Local\Temp\tmp-5164wBfCIzGL8Bvb
.txt'
node-tesseract: Preprocessor cleanup
Question resized
node-tesseract: Running 'tesseract question.jpg C:\Users\Admin\AppData\Local\Tem
p\tmp-5164Gr08LXyb7nOI'
node-tesseract: Deleting 'C:\Users\Admin\AppData\Local\Temp\tmp-5164Gr08LXyb7nOI
.txt'
node-tesseract: Preprocessor cleanup
The question is "   The State Flower of Jharkhand is named after me site of whlc
h famous bafﬂe?  "
Wikipedia link found: https://en.wikipedia.org/wiki/List_of_Indian_state_flowers

C:\Users\Admin\Desktop\HQ-Trivia-Bot\bot.js:58
                                        if($('body').text().toLowerCase().indexO
f(answers[0].toLowerCase()) != -1) {

             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Request._callback (C:\Users\Admin\Desktop\HQ-Trivia-Bot\bot.js:58:94)
    at Request.self.callback (C:\Users\Admin\Desktop\HQ-Trivia-Bot\node_modules\
request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Admin\Desktop\HQ-Trivia-Bot\node_modules\re
quest\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Admin\Desktop\HQ-Trivia-Bot\node_mo
dules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by PoonamChohdhary1991** [comment]
![question](https://user-images.githubusercontent.com/36765468/37912155-ab1f2ae8-30c6-11e8-8c80-cf175663fa8e.jpg)
![answers](https://user-images.githubusercontent.com/36765468/37912162-aed5176a-30c6-11e8-8a43-155d2f382b9e.jpg)

**Comment by nanip9997** [comment]
Can you please clarify the process I was unable to get question.jpg and cannot set the coordinates right if possible make a screen recording it would help a lot of us

**Comment by maxenxe** [comment]
This error means it somehow can't read the answers, https://www.youtube.com/watch?v=QzdqT0HTGLs small vid that shows the setup

**Comment by nanip9997** [comment]
The coordinates that he got are not working when I does the same thing any
suggestions ?

**Comment by maxenxe** [comment]
Yep because the coordinates are different for every user, try looking at answer.jpg and question.jpg or screenshot.jpg to see what is the problem and play with the values
