### ISSUE TITLE
HELP this is the error i get

### ISSUE THREAD

**Issue by Anishrajeev210** [maxenxe/HQ-Trivia-Bot#3]
Anishs-MacBook-Pro:HQ-Trivia-Bot-master anish$ npm start

> hqtriviabot@1.0.0 start /Users/anish/Downloads/HQ-Trivia-Bot-master
> node bot.js

Screenshot done
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "351x233+606+334" "answers.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/anish/Downloads/HQ-Trivia-Bot-master/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by maxenxe** [comment]
Try reinstalling it ( `npm install -g gm`)

**Comment by maxenxe** [comment]
Hey if it doesn't work, add it to your environment variables (https://stackoverflow.com/questions/7501678/set-environment-variables-on-mac-os-x-lion) 
The module path should be `/usr/local/lib/node_modules`, if it doesn't work again, try to install GraphicsMagik (http://www.graphicsmagick.org/INSTALL-unix.html)

**Comment by maxenxe** [comment]
Any news ?

**Comment by TheLazyFreqHog** [comment]
HI Maxenxe, Garry Here. I am having the exact same problem. I tried re-installing. I also have all the items added to the environment.
C:\HQ-Trivia-Bot-master>node bot.js
Screenshot done
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "351x233+606+334" "answers.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\HQ-Trivia-Bot-master\node_modules\gm\lib\command.js:232:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.cp.emit (C:\HQ-Trivia-Bot-master\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)


Any Idea what I could do next?

thanks!

**Comment by maxenxe** [comment]
Yep, it means that the tesseract path isn't in your environment variable named "path", I'll make a video soon to explain in details how to install this bot

**Comment by Anishrajeev210** [comment]
if i am on mac how would i install graphicmagik?

**Comment by MarcoSilva20** [comment]
HI Maxenxe. I am having the exact same problem. I tried re-installing. I also have all the items added to the environment. Already a solution?
