### ISSUE TITLE
Cannot find module 'desktop-screenshot'

### ISSUE THREAD

**Issue by enegronjr** [maxenxe/HQ-Trivia-Bot#30]
C:\JavaScriptPrograms\HQ-Trivia-Bot>node bot.js
module.js:545
    throw err;
    ^

Error: Cannot find module 'desktop-screenshot'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\JavaScriptPrograms\HQ-Trivia-Bot\bot.js:1:80)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by maxenxe** [comment]
Look at the vid in readme
