### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by thenerdbox** [maxenxe/HQ-Trivia-Bot#38]
Run into problems after screenshot is resized.

TypeError: Cannot read property 'toLowerCase' of undefined
    at Request._callback (C:\Users\Miles\Desktop\HQ-Trivia-Bot-master\bot.js:68:94)
    at Request.self.callback (C:\Users\Miles\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Miles\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Miles\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by maxenxe** [comment]
It means that the coordinates aren't correctly set, https://www.youtube.com/watch?v=QzdqT0HTGLs look at this vid
