### ISSUE TITLE
bot error  PLEASE help 

### ISSUE THREAD

**Issue by yusuke20** [maxenxe/HQ-Trivia-Bot#43]
/ Reading screenTraceback (most recent call last):
  File "C:\Users\garyyu\Desktop\HQ_Bot-master\answer_bot.py", line 288, in <module>
    get_points_live()
  File "C:\Users\garyyu\Desktop\HQ_Bot-master\answer_bot.py", line 266, in get_points_live
    question,options=parse_question()
  File "C:\Users\garyyu\Desktop\HQ_Bot-master\answer_bot.py", line 119, in parse_question
    text = read_screen()
  File "C:\Users\garyyu\Desktop\HQ_Bot-master\answer_bot.py", line 100, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\garyyu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\garyyu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\garyyu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\garyyu\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\garyyu\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by HYaz0** [comment]
same issue here

**Comment by maxenxe** [comment]
This isn't the directory from my bot... My bot is named HQ-Trivia-Bot
