### ISSUE TITLE
I Get this error while trying to get the bot to work

### ISSUE THREAD

**Issue by GBeasly** [maxenxe/HQ-Trivia-Bot#68]
Microsoft Windows [Version 10.0.16299.579]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\111\Documents\hq\HQ-Trivia-Bot>bot.js

C:\Users\111\Documents\hq\HQ-Trivia-Bot>node bot.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'desktop-screenshot'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\111\Documents\hq\HQ-Trivia-Bot\bot.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

C:\Users\111\Documents\hq\HQ-Trivia-Bot>

![untitled](https://user-images.githubusercontent.com/41973394/43491847-eb7a2c60-952e-11e8-8989-f342e9d9e268.png)

**Comment by GBeasly** [comment]
i did what the video told me to do btw even though in the video he installed a diffrent tesseract the way he installed it dosent exist anymore
